---
- name: check pve-manager version
  pkg_check:
    name: pve-manager
  register: proxmox_noenterprise__v_package

# remove the crap
- name: patch perl module
  replace:
    path: "{{ proxmox_noenterprise__pm_path }}"
    regexp: "return if\\s+.*PermitRootLogin.*;$"
    replace: "return;"
    backup: yes
  when: proxmox_noenterprise__v_package.installed
