---
- name: converge {{ item }}
  template:
    src:   "systemd/{{ item }}.j2"
    dest:  "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode:  0644
  with_items:
    - fstrim-task.service
    - fstrim-task.timer
  notify: restart fstrim-task.timer
