---
- name: create upper directories for homedirs
  file:
    path: "{{ item.value.home |dirname }}"
    state: directory
    owner: root
    group: root
    mode:  0755
  when: item.value.home is defined
  with_dict: "{{ common_users__list }}"

- name: converge user {{ item.key }}
  user:
    name:     "{{ item.key }}"
    home:     "{{ item.value.home |default(None) }}"
    skeleton: "{{ item.value.skeleton |default('no') }}"
    system:   "{{ item.value.system |default('no') }}"
    password: "{{ item.value.password |default('*') }}"
  when: item.value.home is defined
  with_dict: "{{ common_users__list }}"

- include: user_ssh_keys.yml
  vars:
    common_users__v_user: "{{ item.key }}"
    common_users__v_ssh_keys: "{{ item.value.authorized_keys }}"
  when: item.value.authorized_keys is defined
  with_dict: "{{ common_users__list }}"
